language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: npm
  email: tewson.seeoun@gmail.com
  api_key:
    secure: D5L0Ifdw04t6A5h2p/7zT3usDDOzjGlQA7aPxivMfuuvp7NN2Kdf9xWOJkeucDze80ZAu/zXorf4+VXnggY7aHJeRfMb/5axouocdM1O5Csuwq6t80gzQdEu/luEo/DV0o0aNsNRF8LyUjfMtbdJRCk4T9yG9Qq/S7H17teGEH4/SYOO4qrqYu/C4TmJ32EM316xVwjl+NpxhE27Z8aWf5IWFI6STbDItBUs2ZdySrljWiGf+48T9JeESnagpywjvyBrXRoqXHwV3pQHzQbzpS0yFPHMZZRfzv55h+pcBw1VRtpBjaz/6Wm0sPq59o8o7+wXiCye6AHVXVCqZN1DUsUNTCCLZRkFS7lXdLRzlfp4ODqQidhYwyIaRHz+iv8Gs+tHWMtJ6HtSIPubWwO6XymtbJEPQ56pFoNjDp+kzKR5IhxwnUP8emTz5c5Rkb2ctyDi9hr9PmbuAmuY5FxFCtDQVnmEm3rTuBruP3dptyD02id0QnCYi9cYFWbfiRyq+GPNcgzlrAAhZmfbrQyWQlmYAy4pZtP1+e2K+2NA2zRJxw6Yx64GsqvzqGC56edaz6OzsY4RHDuq8kawqUSI4UHK1NjWkH4kHBdYGMTQSs2T3X1YkkSZX5QhV6rDgyYos3oniobzU0CkfI14ZJkUO9++SqQm2sMLdpSYkGqXle4=
  on:
    tags: true
    repo: tewson/email-box
